### ISSUE TITLE
ADD LABELS GSSOC AND HACKTOBERFEST 

### ISSUE THREAD

**Issue by alo7lika** [Data-Sculptor-X/VOJ-ReactJS#11]
![Screenshot 2024-10-06 130444](https://github.com/user-attachments/assets/7d7c12d4-8118-4f82-ac2c-c2dceda8ea60)
![Screenshot 2024-10-06 205845](https://github.com/user-attachments/assets/2196c08d-f366-4a9e-8f94-795010098869)

ADD LABELS ALSO ON THIS ISSUE hacktoberfest and GSSOC ext 24 .

**Comment by alo7lika** [comment]
ADD LABELS ALSO ON THIS ISSUE hacktoberfest and GSSOC ext 24 .

**Comment by Dbrightson** [comment]
Thanks for bringing this to my attention @alo7lika . I have done it.
