### ISSUE TITLE
Responsiveness feature

### ISSUE THREAD

**Issue by Bhum-ika** [Data-Sculptor-X/VOJ-ReactJS#14]
![image](https://github.com/user-attachments/assets/d30fcce7-f2c8-4a3a-813e-a109c7b6037a)

I would like to work on it.
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by Prithwi32** [comment]
@Bhum-ika I'm assigning you go for it..All the best :)

**Comment by Bhum-ika** [comment]
Thank you prithvi, I expect you to attach correct tags while merging my PR too. 
Thanks

**Comment by Shalinis19137** [comment]
I really like your website and want to contribute can you assign me this issue under gssoc-ext2024

**Comment by Prithwi32** [comment]
@Bhum-ika would u like to contribute to this issue, or shall i transfer to next person?

**Comment by Bhum-ika** [comment]
You can transfer it to next person

**Comment by Prithwi32** [comment]
@Shalinis19137 I assigned this issue to u, u can go for it..All the best 🙌

**Comment by Shalinis19137** [comment]
Thanks sir.
