### ISSUE TITLE
Scroller on Signup Page

### ISSUE THREAD

**Issue by aditya-singhhh** [Data-Sculptor-X/VOJ-ReactJS#16]
<img width="438" alt="image" src="https://github.com/user-attachments/assets/cd604511-14cd-4c28-bb22-94f274f355cf">

Issue - SignUp Button is not properly on all screen size. In this image it is half cut from bottom.
Solution - We can make the component scrollable.

I would like to work on this issue.

**Comment by Prithwi32** [comment]
@aditya-singhhh I saw ur other issue too, [#15](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues/15), fix these too with responsiveness of login, signup forms...I'm assigning you, All the best 👍
