### ISSUE TITLE
Auto Commenting on closing of An issue

### ISSUE THREAD

**Issue by sejals23** [Data-Sculptor-X/VOJ-ReactJS#23]
Auto-commenting is a feature that automatically posts a comment when an issue is closed in a repository.
When the issue is closed, a pre-defined comment will be automatically posted, acknowledging the closure.
The action will run every time an issue is closed, without needing manual input.

Auto-comments ensure that every closed issue receives a response, maintaining a consistent communication standard.
Automating this process helps maintainers focus on coding and fixing issues, rather than manually writing a comment for every closed issue.

**Comment by Prithwi32** [comment]
@sejals23 I'm assigning you, u can go for it ...All the best!!

**Comment by Prithwi32** [comment]
@sejals23 are u participating under gssoc-ext pr hacktoberfest?

**Comment by EvanSingee** [comment]
Can I work on this issue pls @Prithwi32

**Comment by Prithwi32** [comment]
@sejals23 are u working on issue..?
If not will be reassigned next person

**Comment by sejals23** [comment]
I ll do it by today

**Comment by EvanSingee** [comment]
@Prithwi32 can you reassign pls

**Comment by EvanSingee** [comment]
@Prithwi32
