### ISSUE TITLE
BUG: Login Page Bug

### ISSUE THREAD

**Issue by RudrasSingh** [Data-Sculptor-X/VOJ-ReactJS#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Topic

Login page issue with the UI

Details

The login page has a login button that is mis-aligned and the fields of the signup and signin form are not mandetory fields, which is leading to the trigger of signup/signin function causing potentian backend issue.
This can be fixed simply by some simple changes!

Additional context

Adding the before and after screenshots of the issue.
Before:
![Screenshot 2024-10-12 020611](https://github.com/user-attachments/assets/a3731a89-7ff4-4a28-a165-2f6e947b2a11)

After:
![Screenshot 2024-10-12 020535](https://github.com/user-attachments/assets/e13e8493-841f-465f-8bb3-de4367648182)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@RudrasSingh it's actually covered in one of already existing issue #14 ..so feel free to raise issues qhich r not present... Thank you
