### ISSUE TITLE
Feat:Enhance Sign up and Login Page

### ISSUE THREAD

**Issue by devxMani** [Data-Sculptor-X/VOJ-ReactJS#28]
### Describe the feature

Enhancing the UI of pages without deleting any logic or data

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f83ded02-f59e-4921-8996-b02b8c6710f5)

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Dbrightson** [comment]
@devxMani Hi Mani, Thanks for bringing this into our notice, I'll assign you this task, but please ensure that you don't accidentally change any logic.

**Comment by devxMani** [comment]
@Dbrightson ok I'll make sure
