### ISSUE TITLE
Enhancement: Add hover effect to the signup and sign-in buttons for better user interaction

### ISSUE THREAD

**Issue by sanchitc05** [Data-Sculptor-X/VOJ-ReactJS#29]
### Describe the feature

**Description:**
Hello,

I noticed that while the *Voice Of Justice* website is well-designed, the signup and sign-in buttons appear static. I believe adding a hover effect to these buttons would make them more dynamic and engaging, improving user interaction and enhancing the overall user experience.

I’d be happy to help implement this hover effect if you're open to the suggestion. Let me know your thoughts!

Best regards,  
Sanchit

### Add ScreenShots

![Screenshot (236)](https://github.com/user-attachments/assets/f1520eeb-7d72-4ddf-8262-c620628e86a8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Dbrightson** [comment]
@sanchitc05 Hi, Thanks for the offer, but I really think that would be necessary at this point, I'm closing this issue ... you can reopen it if you can bring enhancement to any other component.
Please keep in mind, that this program is to develop your learning experience as well, go for a big fish, not small ones like these!

I believe in you Sanchit, Good luck!
