### ISSUE TITLE
DOC:Improving the README for "Voice of Justice" (VOJ) Project

### ISSUE THREAD

**Issue by daud0x0** [Data-Sculptor-X/VOJ-ReactJS#30]
### What's wrong with the existing documentation

Missing Installation and Setup Instructions: The README does not explain how a user can run the project locally or test it. There's no guidance on setting up the development environment or dependencies.

### Add ScreenShots

![Screenshot from 2024-10-15 22-44-46](https://github.com/user-attachments/assets/8582155a-b95a-4dfa-b997-0c76aaba27f5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@daud0x0 did u done setup in your pc?

**Comment by daud0x0** [comment]
I tried but failed to run (node 20)
![image](https://github.com/user-attachments/assets/8b299764-d15a-41a7-bd43-1f9ad6cad8bc)

**Comment by Prithwi32** [comment]
> I tried but failed to run (node 20) ![image](https://private-user-images.githubusercontent.com/85936724/377108204-8b299764-d15a-41a7-bd43-1f9ad6cad8bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTA1NjgsIm5iZiI6MTcyOTA5MDI2OCwicGF0aCI6Ii84NTkzNjcyNC8zNzcxMDgyMDQtOGIyOTk3NjQtZDE1YS00MWE3LWJkNDMtMWY5YWQ2Y2FkOGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE0NTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5M2M0NjcxOTgyNTBmZjRjZGZhYmIxYmY5ODc5MGQxMmE0MjA4NjBlOWZjZjM2OTUyZDJiZTMxZmExZmQ4NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LxvRJlPB5uc5Fw8l3lfGGsDOGeG5JbzHGejKvZRAPAY)

npm i, did u run?

**Comment by daud0x0** [comment]
yess

**Comment by Prithwi32** [comment]
> yess

@daud0x0 feel free to get on discussion in discussion section

**Comment by Prithwi32** [comment]
@daud0x0 `npm install ajv@latest ajv-keywords@latest` use this command to update to new version, then npm start to run react app
