### ISSUE TITLE
Feat: Clarify this doubt so that I can open a new issue.

### ISSUE THREAD

**Issue by TheUsefulNerd** [Data-Sculptor-X/VOJ-ReactJS#31]
### Describe the feature

Is "AI Assisted Legal Consultation" or any AI part of this project implemented? If yes, In which folder can I find the files related to it?
If they are not implemented yet, are there any ideas that you have that you want in this project?

### Add ScreenShots

![image](https://github.com/user-attachments/assets/40a331ab-24d1-4568-a09f-2f954d412c32)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by TheUsefulNerd** [comment]
Also can you please make a discussions section in this repo to clarify doubts and to interact with ppl?

**Comment by Dbrightson** [comment]
1. We have used OpenAI's API and fine-tuned it to answer legal queries, it's already implemented, and we kindly request you to not touch that functionality alone.
2. We'll definitely create a discussions forum in this repository, thanks for the suggestion!
