### ISSUE TITLE
DOC: Minor changes in Readme.md file

### ISSUE THREAD

**Issue by memoizedk** [Data-Sculptor-X/VOJ-ReactJS#34]
### What's wrong with the existing documentation

I viewed the Readme.md file and there was a minor error where the formatting of a headline didn't match with others. It really gives an unorganized sight. I would like to format it to make it look even with the other headings.
Kindly assign this to me.
Thanks :-) 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d2589908-f313-4e98-b7f7-6f742f3503a9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@khushidadwal I suggest you to work on good issues, instead of these minor corrections...
