### ISSUE TITLE
Feat:Enhancing the Login and Sign up pages according to the recent changes

### ISSUE THREAD

**Issue by devxMani** [Data-Sculptor-X/VOJ-ReactJS#36]
### Describe the feature

Adding transitions effects and other changes without deleting any logic 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/839e938e-b636-4502-aa21-cd1fe8a79838)
![image](https://github.com/user-attachments/assets/2805568f-0d1a-4ded-b580-17fd15a078e5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@devxMani feel free to raise good issue...Thanks!
