### ISSUE TITLE
Feat:adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by trahulprabhu38** [Data-Sculptor-X/VOJ-ReactJS#37]
### Describe the feature

I want to add a page to showcase all the contributors of this website.
can you assign me this issue,

### Add ScreenShots

=

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
Issue will be closed by #38
