### ISSUE TITLE
Feat : Adding multi language support system✨

### ISSUE THREAD

**Issue by trahulprabhu38** [Data-Sculptor-X/VOJ-ReactJS#38]
### Describe the feature

I want to add multi language support system to the website which can help us understand in their native language.

### Add ScreenShots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@T-Rahul-prabhu-38 u mean multi language option for chatbot system....?

**Comment by trahulprabhu38** [comment]
no
the website languages can be changed with this

**Comment by trahulprabhu38** [comment]
this helps native speakers access this website in thier language

**Comment by Prithwi32** [comment]
> this helps native speakers access this website in thier language

Okay for whole website?
Specific mutli language access in which section of website...we can assign u

**Comment by trahulprabhu38** [comment]
it changes all the words of the website

**Comment by trahulprabhu38** [comment]
it supports 200+ languages so it can be toggled btw that.

**Comment by Prithwi32** [comment]
@T-Rahul-prabhu-38 LGTM, I'm assigning you, All the best..u can also implement #37 as well in same PR, assigned level3 totally...

**Comment by Prithwi32** [comment]
@Dbrightson could u confirm once feature

**Comment by trahulprabhu38** [comment]
@Prithwi32 sure , i didnt read this message ill do the necessary changes .

**Comment by Dbrightson** [comment]
@Prithwi32 Hi, sorry for responding late, yeah I think we can proceed with this. No worries

**Comment by Prithwi32** [comment]
> message

It's okay.. It's already completed now
