### ISSUE TITLE
Adding an AI chatbot 

### ISSUE THREAD

**Issue by balbirs22** [Data-Sculptor-X/VOJ-ReactJS#39]
### Describe the feature

I want to add an AI chatbot using python which can later be integrated with the original website 

### Add ScreenShots

If you agree I will proceed with this 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by lakshaymittal45** [comment]
I am really excited to contribute to this project, Looking forward to contribute to this amazing project
