### ISSUE TITLE
#Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [Data-Sculptor-X/VOJ-ReactJS#4]
I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext and level1 Labels.

**Comment by devarsheecodess** [comment]
Please assign this to me with gssoc-extd label. i can do this for you

**Comment by Pavitra-s-Workspace** [comment]
I'm interested in contributing to this project.  please assign me this issue

**Comment by Dbrightson** [comment]
Go ahead @KiranBaliga , given you the green light!

**Comment by KiranBaliga** [comment]
@Dbrightson will work on this. I will raise the PR by tomorrow morning max as I have to sketch from scratch. Will be using a standard template for reference and modifying it based on the project. Please give me the support email ID to be added to the markdown file for reporting purposes for the users.

**Comment by Dbrightson** [comment]
Sure! Take your time Kiran

**Comment by KiranBaliga** [comment]
@Dbrightson Please review the PR and action accordingly. Please edit the label from -gssoc-ext to gssoc-ext for this PR and others as well. Thank you so much!

**Comment by Dbrightson** [comment]
Done Kiran. Thank you so much for your contributions!

**Comment by KiranBaliga** [comment]
@Dbrightson Thank you. But apologies, for requesting again, please add level1 label and gssoc-ext label to the PR as well. I duly understand that you have added to the issue but the leaderboard accepts labels directly from the PR. So eventhough you added the labels here, it would not be counted for me. 

So I sincerely request to add level1 and gssoc-ext directly to the PR as well.

This will help me and fellow contributors as well and upcoming PR's to your repo.

Thank you for your kind understanding!

**Comment by Dbrightson** [comment]
HI @KiranBaliga , I have added the labels to the PRs as well, hope it works now!
