### ISSUE TITLE
Feat:Add Donation And Funding portal 

### ISSUE THREAD

**Issue by falak412** [Data-Sculptor-X/VOJ-ReactJS#45]
### Describe the feature

Donation and Funding Portal
Support the Community: Include a donation feature where users or external parties can contribute to help fund the platform's operations or support specific cases.
Transparency Reports: Regularly update users on how the donations are being utilized to improve the platform and provide legal assistance.
@Data-Sculptor-x/ please assign me this issue.
Gssoc'24 extended .

### Add ScreenShots

Provide suggested donation amounts along with a brief explanation of how each amount can benefit the platform or its users.Send personalized thank-you notes to donors, highlighting the specific impact their contribution has made.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Dbrightson** [comment]
@falak412 Hi Falak, but we already have a donation feature for this project!
