### ISSUE TITLE
DOC:Adding Contributing.md file

### ISSUE THREAD

**Issue by Nikhil0-3** [Data-Sculptor-X/VOJ-ReactJS#47]
### What's wrong with the existing documentation

By adding the file
I want to add the following points-
Project Overview
How to Contribute
Contribution Guidelines
Opening a Pull Request
Issue Report Process
Technologies Used
Community and Communication
Project Structure
Inspiration for Contributions

Also , I will try to make it more interactive.
If any further changes required please tell me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@Nikhil0-3 some of you mentioned are already implemented..please look into issue before creating one..Thank you

**Comment by Nikhil0-3** [comment]
Okay
But, I will try to make it more interactive 
Please give me a chance.
Thank you

**Comment by Prithwi32** [comment]
> Okay But, I will try to make it more interactive Please give me a chance. Thank you

how will u be making it interactive..let me know approach first

**Comment by Nikhil0-3** [comment]
I added the screenshot of  the  code_of_conduct file on which I had contributed earlier

![Screenshot_20241021_234009_Chrome](https://github.com/user-attachments/assets/ad6671d4-0561-40a7-a12a-36f113a00d6c)
![Screenshot_20241021_233958_Chrome](https://github.com/user-attachments/assets/f9a01a2d-54a5-4a11-a1b0-2ca5258eec9a)

**Comment by Nikhil0-3** [comment]
Contributing.md file was not there.
This file helps contributors that which steps they should uld follow while raising a PR.

I already contributed to one of the project,
Here i attached the screenshot of that
![Screenshot_20241021_235433_Chrome](https://github.com/user-attachments/assets/48a42313-113c-4437-8fd0-fd93914f2f88)
![Screenshot_20241021_235448_Chrome](https://github.com/user-attachments/assets/1c2d3331-00e2-48ba-8be1-d2f66ef5bb34)
![Screenshot_20241021_235458_Chrome](https://github.com/user-attachments/assets/06d29566-b000-459f-a6ae-76df05078e65)
![Screenshot_20241021_235502_Chrome](https://github.com/user-attachments/assets/59b70500-f202-4dae-97c0-8eef446ba84e)
