### ISSUE TITLE
#Add Github Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [Data-Sculptor-X/VOJ-ReactJS#5]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24 Contribution)

**Comment by Dbrightson** [comment]
Thanks for this amazing offer @KiranBaliga , go ahead...I have assigned you the task!

**Comment by KiranBaliga** [comment]
@Dbrightson Please review the PR and action accordingly. Thank you! Please add level1 and gssoc24-ext to the PR as well. Thanks again
