### ISSUE TITLE
Feat: I want to add MIT License

### ISSUE THREAD

**Issue by Susmita0202** [Data-Sculptor-X/VOJ-ReactJS#51]
### Describe the feature

want to add MIT License

### Add ScreenShots

![Screenshot 2024-10-22 001626](https://github.com/user-attachments/assets/3d00fbee-5310-4123-a881-011419f02711)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Dbrightson** [comment]
@Susmita0202 Hello, the MIT License grants the following permissions:

1. Freedom to use: The software may be used for any purpose.
2. Freedom to modify: The software can be modified to meet your needs.
3. Freedom to distribute: You are allowed to distribute original or modified copies of the software.
4. Freedom to sublicense: The software can be sublicensed.
5. Freedom to sell: Copies of the software may be sold.

However, we are opting for a Proprietary license, which allows for modification, use, and distribution, but restricts resale and sublicensing.

I trust this clarifies things! You're welcome to contribute in other ways!
