### ISSUE TITLE
DOC: Enhancement in code_of_conduct.md file

### ISSUE THREAD

**Issue by Nikhil0-3** [Data-Sculptor-X/VOJ-ReactJS#52]
### What's wrong with the existing documentation

I want to add following points- 
Our Pledge
Our Standards
Enforcement Responsibilities
Scope
Pull Request Guidelines
Enforcement
Enforcement Guidelines
Attribution
Conclusion
Also , I will try to make it more creative.
If any further changes required please tell me.

### Add ScreenShots

I want to make your file like this

![Screenshot 2024-10-23 082426](https://github.com/user-attachments/assets/8d22a338-2ba2-4069-8404-297c0267729b)

![Screenshot 2024-10-23 082438](https://github.com/user-attachments/assets/48051b19-dfe5-4d0c-bc70-be57d91d2f07)
![Screenshot 2024-10-23 082448](https://github.com/user-attachments/assets/39bea019-6e8a-48b9-aca1-8d0ad9adebbd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
Sorry, it's a repetition of the issue. We are currently giving preference for enhancement of features more.

**Comment by Prithwi32** [comment]
> Sorry, it's a repetition of the issue. We are currently giving preference for enhancement of features more.

I understand your issue, but we truly appreciate you contributing towards features, rather than correcting the Readme file, where u will get more ways to learn and contribute..Thank you!
