### ISSUE TITLE
DOC: Mention how to Run this software after cloning.

### ISSUE THREAD

**Issue by Anushka-Pote** [Data-Sculptor-X/VOJ-ReactJS#54]
### What's wrong with the existing documentation

There is the session about how to merge the new commits, but not how to run this on the various IDEs. I think it's needed as some contributors are beginner level, but if it doesn't seem a necessity it's still okay

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@Anushka-Pote It's not many issues considered as a quality, It's understood by developers how to run project!
Feel free to contribute towards features
