### ISSUE TITLE
DOC : Documentation: Wanted To Add Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [Data-Sculptor-X/VOJ-ReactJS#57]
### What's wrong with the existing documentation

I wanted to add the contributing.md file which will help the contributors to easily contribute. It will also help them understand the correct way of following coding practices and other important things.

Wanted to do the following changes :-

1) Enhance the project structure
2) Add code of conduct section
3) Add star our repository section
4) Add need help with the basics section
5) Add first pull request steps section
6) Add additional method of contributing through GitHub desktop section
7) Add good coding practices section
8) Add the pull request rules section
9) Add the thank you section

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
I understand your points, but we truly appreciate you contributing towards features, rather than correcting to documention,  where u will get more ways to learn and contribute..Thank you!

**Comment by Prithwi32** [comment]
@milansamuel609 could you brief it about about ur 1st point mentioned?
How u want to change project structure to?

**Comment by milansamuel609** [comment]
Basically I will do the documentation in a fully ordered and systematic manner 
(Ex :- the headers, point wise manner, correct way of aligning codes where needed line by line instead of 2 codes together) 
so that it will not make a single confusion for the contributors just that nothing else 👍.

**Comment by milansamuel609** [comment]
> @milansamuel609 could you brief it about about ur 1st point mentioned? How u want to change project structure to?

Basically I will do the documentation in a fully ordered and systematic manner
(Ex :- the headers, point wise manner, correct way of aligning codes where needed line by line instead of 2 codes together)
so that it will not make a single confusion for the contributors just that nothing else 👍.

**Comment by Prithwi32** [comment]
> > @milansamuel609 could you brief it about about ur 1st point mentioned? How u want to change project structure to?
> 
> Basically I will do the documentation in a fully ordered and systematic manner (Ex :- the headers, point wise manner, correct way of aligning codes where needed line by line instead of 2 codes together) so that it will not make a single confusion for the contributors just that nothing else 👍.

It doesn't mean project structure, it means u want to do code refactor..
Sorry we are focusing on quality contributions..
Feel free to work on features.. that we encourage..
