### ISSUE TITLE
🚀 Automate Connections with GitHub Actions!

### ISSUE THREAD

**Issue by amiya-cyber** [Data-Sculptor-X/VOJ-ReactJS#58]
We can implement github workflows for the following things:

Auto comment on issue Closed and Opened
Auto comment on PR mergs
Auto comment on PR raises
Using this workflows makes you'r repo more interactive !

please assign me and i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label

**Comment by Prithwi32** [comment]
> We can implement github workflows for the following things:
> 
> Auto comment on issue Closed and Opened Auto comment on PR mergs Auto comment on PR raises Using this workflows makes you'r repo more interactive !
> 
> please assign me and i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label

@amiya-cyber some of the workflows u mentioned are already implemented, we are focusing on feature enhancements, it would be great if u work on that .. Thank you :)
