### ISSUE TITLE
Feat:Enhance readme.md with Statistics table 

### ISSUE THREAD

**Issue by laxmikandivalasa** [Data-Sculptor-X/VOJ-ReactJS#59]
### Describe the feature

When a project is opened...it's readme file is viewed by any contributors or users...
so to have a great opinion and positive response for the website....a good readme is must and should
a table that shows statistics like the count of forks, pull requests (PRs), issues, stars, and other repository stats. This is often used to give readers a quick overview of the project’s activity and popularity

### Add ScreenShots

I'd like to add this to your readme that enhance it to another level
![Screenshot 2024-10-30 135011](https://github.com/user-attachments/assets/93ff0e11-a003-4457-81d7-f2a40d6e0b04)
can you assign this to me
I'd like to contribute to your website!!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
we are focusing on feature enhancements, it would be great if u work on that .. Thank you :)
