### ISSUE TITLE
Adding metrices table and program section

### ISSUE THREAD

**Issue by Aman-G-upta** [Data-Sculptor-X/VOJ-ReactJS#60]
![Screenshot 2024-10-26 185138](https://github.com/user-attachments/assets/985bd13b-ecdf-40ba-aa0d-3a5b378efe65)
Please assign me under this issue @Data-Sculptor-X

**Comment by Prithwi32** [comment]
@Aman-G-upta we are focusing on feature enhancements, it would be great if u work on that .. Thank you :)
