### ISSUE TITLE
DOC: Adding a Project Structure Map 

### ISSUE THREAD

**Issue by siri-chandana-macha** [Data-Sculptor-X/VOJ-ReactJS#62]
### What's wrong with the existing documentation

Adding a clear structure map in the documentation to guide contributors on where specific files and folders are located and what they contain.
This helps new contributors quickly understand the project layout and find files easily.

### Add ScreenShots

**For example:**

Project Root
├── src/ &nbsp;&nbsp;&nbsp;&nbsp;              # Core application files
│ ├── components/ &nbsp;&nbsp;&nbsp;&nbsp;                         # Reusable UI components
│ ├── services/ &nbsp;&nbsp;&nbsp;&nbsp;                                # API calls and business logic
│ ├── utils/ &nbsp;&nbsp;&nbsp;&nbsp;                                     # Utility functions
│ └── index.js  &nbsp;&nbsp;&nbsp;&nbsp;                               # Main entry file
├── assets/ &nbsp;&nbsp;&nbsp;&nbsp;                                   # Images, icons, and other static assets
├── config/    &nbsp;&nbsp;&nbsp;&nbsp;                                 # Configuration files (e.g., env variables)
└── README.md   &nbsp;&nbsp;&nbsp;&nbsp;                          # Project overview and instructions

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@siri-chandana-macha we are focusing on feature enhancements, it would be great if u work on that .. Thank you :)
