### ISSUE TITLE
Adding a deployment link in the github repository

### ISSUE THREAD

**Issue by NANDAGOPALNG** [Data-Sculptor-X/VOJ-ReactJS#63]
### What's wrong with the existing documentation

when people come to repo they do not find deployment link in activity section which is not convinient, which is a major set back for the potential of this amazing project, so I will add it in convinient way possible

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
this issue will be completed in #64
