### ISSUE TITLE
DOC:Add security policy in.md file 

### ISSUE THREAD

**Issue by Dipanita45** [Data-Sculptor-X/VOJ-ReactJS#66]
### What's wrong with the existing documentation

Nothing 
Want to add security policy to protect the website against the harms 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
- [X] I'm a GSSOC'24-Extended contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@Dipanita45 I understand your issue, but we truly appreciate you contributing towards features, rather than correcting the Readme file, where u will get more ways to learn and contribute..Thank you!
