### ISSUE TITLE
The site dosen't have wesite link for navigation.

### ISSUE THREAD

**Issue by bjamre13** [Data-Sculptor-X/VOJ-ReactJS#7]
Assign me this so i can resolve this.

**Comment by ChauhanAyush04** [comment]
Plz assign me this

**Comment by tanu91112** [comment]
Plz assign me with this task ,i will resolve this issue.

**Comment by bjamre13** [comment]
@Data-Sculptor-X kindly assign this asap.!

**Comment by Prithwi32** [comment]
@bjamre13 let me know in brief, the issue u raised about?

**Comment by bjamre13** [comment]
It was about the deployment link for the website.!
So the user can be easily navigated.

**Comment by Prithwi32** [comment]
@bjamre13 it will be done by redme file itself..so please find other issues to assign fro you
