### ISSUE TITLE
add readme

### ISSUE THREAD

**Issue by Ayushj0704** [Data-Sculptor-X/VOJ-ReactJS#8]
add readme file in detail to know more about the project

**Comment by Dbrightson** [comment]
Hi @anushka4124 ,

Thank you for offering to contribute! I'll provide you with access so you can start right away. Could you please share your LinkedIn profile? We're excited to enhance our app with more functionalities and would love to have you join us on this journey.

**Comment by anushka4124** [comment]
sure! @Dbrightson 
here's my linkedin profile:
https://www.linkedin.com/in/anushkabhattacharji

Also, along with assigning me this task, can you please label this under tags like - gssoc-ext and hacktober-accepted

**Comment by anushka4124** [comment]
thank you so much for assigning me this task! @Dbrightson 

Can you  please label this under tags like - gssoc-ext and hacktober-accepted ???

**Comment by Dbrightson** [comment]
Sure Anushka. I have labeled it, also great job winning the JPMC Code for Good and congrats on securing an internship at JPMC. Your works are amazing, Keep up the good work!

**Comment by anushka4124** [comment]
> Sure Anushka. I have labeled it, also great job winning the JPMC Code for Good and congrats on securing an internship at JPMC. Your works are amazing, Keep up the good work!

Thank you so much for your lovely words! @Dbrightson 
Hope I will be able to meet your expectations in drafting the Readme file.

Actually in our Contributors discord channel, we were told this and were asked to inform the corresponding project admins to keep this in mind:
The correct labels are gssoc-ext, level1, level2, level3, hacktober-accepted, hacktoberfest

Actually these tags are very crucial for us contributers, as we will be evaluated on the same. It would be very kind of you to consider these labels. The level label is completely decided upto you.

**Comment by Prithwi32** [comment]
@anushka4124 may i know your progress?

**Comment by Prithwi32** [comment]
@anushka4124 please could to reply back that whether u r continuing with this issue or not ... asking becoz it's been many days
..and also some people npt able to proceed with entire setup of application....so contribution to project related to feature is carried out less... Please reply back... :)

**Comment by khushidadwal** [comment]
I can't see any development in the readme file. Could you please assign this to me!

**Comment by Dbrightson** [comment]
You've the green flag @khushidadwal , Good luck!

**Comment by khushidadwal** [comment]
Thank you!

**Comment by SaanyaGarg5** [comment]
pls assign this task to me..

**Comment by Prithwi32** [comment]
> pls assign this task to me..

This issue completed..fell free to look into other issues
